from enum import StrEnum


class AIErrorCode(StrEnum):
    disabled = "AI_DISABLED"
    provider_not_found = "AI_PROVIDER_NOT_FOUND"
    provider_unavailable = "AI_PROVIDER_UNAVAILABLE"
    model_not_allowed = "AI_MODEL_NOT_ALLOWED"
    configuration = "AI_CONFIGURATION_ERROR"
    request_invalid = "AI_REQUEST_INVALID"
    context_too_large = "AI_CONTEXT_TOO_LARGE"
    tool_selection = "AI_TOOL_SELECTION_FAILED"
    tool_loop_limit = "AI_TOOL_LOOP_LIMIT_REACHED"
    tool_budget = "AI_TOOL_BUDGET_EXCEEDED"
    provider_timeout = "AI_PROVIDER_TIMEOUT"
    provider_rate_limited = "AI_PROVIDER_RATE_LIMITED"
    provider_auth = "AI_PROVIDER_AUTH_FAILED"
    provider_bad_response = "AI_PROVIDER_BAD_RESPONSE"
    stream_interrupted = "AI_STREAM_INTERRUPTED"
    citation_validation = "AI_CITATION_VALIDATION_FAILED"
    response_empty = "AI_RESPONSE_EMPTY"
    conversation_busy = "AI_CONVERSATION_BUSY"
    conversation_not_found = "AI_CONVERSATION_NOT_FOUND"
    conversation_deleted = "AI_CONVERSATION_DELETED"
    message_not_found = "AI_MESSAGE_NOT_FOUND"
    message_not_regeneratable = "AI_MESSAGE_NOT_REGENERATABLE"
    generation_not_running = "AI_GENERATION_NOT_RUNNING"
    generation_cancelled = "AI_GENERATION_CANCELLED"
    history_too_large = "AI_HISTORY_TOO_LARGE"
    internal = "AI_INTERNAL_ERROR"
