import Foundation
import StockMonitorDesign

// 各业务域的字段目录（R2.1）。登记规则见 `SemanticFieldCatalog.swift`：
// 同一指标在所有页面使用同一中文名称、精度和单位；未登记字段只进入诊断区。

extension SemanticDomainCatalog {
    // MARK: Portfolio

    static let portfolioFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("portfolio_id", "组合标识", .identifier),
        .spec("position_count", "持仓数量", .integer),
        .spec("priced_count", "已估值持仓", .integer),
        .spec("total_market_value", "总市值（基础币种）", .amount(currency: nil)),
        .spec("cash_balance", "账户现金", .amount(currency: nil)),
        .spec("total_net_liquidation", "净清算价值", .amount(currency: nil)),
        .spec("net_asset_value", "净资产", .amount(currency: nil)),
        .spec("invested_market_value", "投资市值", .amount(currency: nil)),
        .spec("cash", "现金", .amount(currency: nil)),
        .spec("total_cost", "总成本", .amount(currency: nil)),
        .spec("total_unrealized_pnl", "总浮动盈亏", .amount(currency: nil)),
        .spec("total_unrealized_pnl_percent", "总浮动盈亏比例", .percent(precision: 2)),
        .spec("ibkr_reported_nav", "IBKR 上报净值", .amount(currency: nil), explanation: "Flex 报告的账户净值，仅在行情缺失时作为兜底显示。"),
        .spec("net_contributions", "净入金", .amount(currency: nil)),
        .spec("investment_pnl", "投资损益", .amount(currency: nil)),
        .spec("simple_cumulative_return", "累计收益率", .percent(precision: 2)),
        .spec("latest_daily_return", "最近日收益", .percent(precision: 2)),
        .spec("month_return", "本月收益", .percent(precision: 2)),
        .spec("year_return", "本年收益", .percent(precision: 2)),
        .spec("time_weighted_return", "时间加权收益", .percent(precision: 2)),
        .spec("dividend_income", "股息收入", .amount(currency: nil)),
        .spec("has_unpriced_positions", "存在无价持仓", .boolean(trueLabel: "有持仓缺行情", falseLabel: "全部有价")),
        .spec("has_unconverted_positions", "存在未折算持仓", .boolean(trueLabel: "有持仓缺汇率", falseLabel: "全部已折算")),
        .spec("fx_conversion_used", "已使用汇率折算", .boolean(trueLabel: "已折算", falseLabel: "未使用")),
        .spec("latest_sync_at", "最近同步", .datetimeText),
        .spec("account_data_source", "账户数据来源", .text, explanation: "ibkr_flex 表示以 IBKR Flex 报告为权威，manual 表示手动账本。"),
        .spec("market_price_source", "行情来源", .text),
        .spec("data_completeness", "数据完整度", .percent(precision: 0)),
        .spec("positions", "持仓列表", .text),
        .spec("security_id", "证券标识", .identifier),
        .spec("total_quantity", "数量", .decimal(precision: 4)),
        .spec("average_cost", "平均成本", .price(precision: 2, currency: nil), explanation: "交易所本币计。"),
        .spec("current_price", "现价", .price(precision: 2, currency: nil)),
        .spec("previous_close", "昨收", .price(precision: 2, currency: nil)),
        .spec("daily_change_amount", "日涨跌", .price(precision: 2, currency: nil)),
        .spec("daily_change_percent", "日涨跌幅", .percent(precision: 2)),
        .spec("market_value", "市值（本币）", .amount(currency: nil)),
        .spec("base_currency_market_value", "市值（基础币种）", .amount(currency: nil), explanation: "跨持仓聚合使用基础币种口径。"),
        .spec("base_currency_total_cost", "成本（基础币种）", .amount(currency: nil)),
        .spec("base_currency_unrealized_pnl", "浮动盈亏（基础币种）", .amount(currency: nil)),
        .spec("portfolio_weight", "组合权重", .percent(precision: 1)),
        .spec("valuation_available", "可估值", .boolean(trueLabel: "可估值", falseLabel: "缺价或汇率")),
        .spec("authority_source", "数量权威来源", .text, explanation: "client_portal_gateway 表示以 Gateway 实时仓位为最高优先级。"),
        .spec("fx_rate", "汇率", .decimal(precision: 4)),
        .spec("fx_rate_source", "汇率来源", .text),
        .spec("price_source", "价格来源", .text),
        .spec("price_as_of", "价格时间", .datetimeText),
        .spec("price_is_delayed", "行情延迟", .boolean(trueLabel: "延迟", falseLabel: "实时")),
        .spec("holding_days", "持有天数", .integer),
        .spec("first_trade_at", "首笔交易", .datetimeText),
        .spec("last_transaction_at", "最近交易", .datetimeText),
        .spec("total_pnl", "总盈亏", .amount(currency: nil)),
        .spec("total_return_pct", "总收益率", .percent(precision: 2)),
        .spec("ibkr_conid", "IBKR 合约号", .identifier),
    ])

    // MARK: Journal

    static let journalFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("trade_date", "交易日", .dateText),
        .spec("direction", "方向", .text),
        .spec("quantity", "数量", .decimal(precision: 4)),
        .spec("price", "价格", .price(precision: 2, currency: nil)),
        .spec("content", "正文", .longText),
        .spec("ai_summary", "AI 总结", .longText),
        .spec("ai_summary_model", "总结模型", .text),
        .spec("ai_summary_created_at", "总结时间", .datetimeText),
        .spec("source_type", "来源类型", .text, explanation: "draft 表示由 IBKR 对账差异自动生成的待写草稿。"),
        .spec("objective_facts", "客观事实", .longText, explanation: "只读的服务端事实，不可被用户编辑覆盖。"),
        .spec("ibkr_sync_run_id", "同步运行", .identifier),
        .spec("photo_urls", "照片", .integer),
    ])

    // MARK: IBKR

    static let ibkrFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("account_id_masked", "账户（脱敏）", .text),
        .spec("latest_sync", "最近同步运行", .text),
        .spec("current_or_last_attempt", "最近尝试", .text),
        .spec("imported_at", "导入时间", .datetimeText),
        .spec("parser_version", "解析版本", .text),
        .spec("section_counts", "各节记录数", .text),
        .spec("import_counts", "导入计数", .text),
        .spec("reconciliation", "对账摘要", .text),
        .spec("propagation", "传播摘要", .text),
        .spec("report_from_date", "报告起始日", .dateText),
        .spec("report_to_date", "报告截止日", .dateText),
        .spec("generated_at_ibkr", "报告生成时间", .datetimeText),
        .spec("account_summary", "账户摘要", .text),
        .spec("net_liquidation", "净清算价值", .amount(currency: nil)),
        .spec("starting_value", "起始价值", .amount(currency: nil)),
        .spec("total_cash", "总现金", .amount(currency: nil)),
        .spec("settled_cash", "已结算现金", .amount(currency: nil)),
        .spec("dividends", "股息", .amount(currency: nil)),
        .spec("interest", "利息", .amount(currency: nil)),
        .spec("buying_power", "购买力", .amount(currency: nil)),
        .spec("available_funds", "可用资金", .amount(currency: nil)),
        .spec("excess_liquidity", "超额流动性", .amount(currency: nil)),
        .spec("initial_margin", "初始保证金", .amount(currency: nil)),
        .spec("maintenance_margin", "维持保证金", .amount(currency: nil)),
        .spec("position_count", "持仓数量", .integer),
        .spec("trade_count", "成交数量", .integer),
        .spec("order_count", "订单数量", .integer),
        .spec("cash_ledger_count", "现金流数量", .integer),
        .spec("archive_exists", "报告归档存在", .boolean(trueLabel: "已归档", falseLabel: "缺失")),
        .spec("missing_sections", "缺失章节", .longText),
        .spec("unrecognized_records", "未识别记录", .integer),
        .spec("duplicate_records", "重复记录", .integer),
        .spec("position_match_rate", "持仓匹配率", .percent(precision: 1)),
        .spec("authority_audit_count", "权威审计条数", .integer),
        .spec("derived_data", "派生数据", .text),
        .spec("portfolio_propagated_at", "组合传播时间", .datetimeText),
        .spec("explicit_gaps", "明确缺口", .longText, explanation: "公司行动、购买力与保证金数据不在 Flex 报告内，属已知缺口。"),
        .spec("gateway_reachable", "网关可达", .boolean(trueLabel: "可达", falseLabel: "不可达")),
        .spec("authenticated", "已认证", .boolean(trueLabel: "已认证", falseLabel: "未认证")),
    ])

    // MARK: Discovery

    static let discoveryFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("current_run", "当前运行", .text),
        .spec("result", "最新结果", .text),
        .spec("using_previous_result", "显示上一成功批次", .boolean(trueLabel: "上一批次", falseLabel: "最新批次")),
        .spec("api_key_configured", "密钥已配置", .boolean(trueLabel: "已配置", falseLabel: "未配置")),
        .spec("discovery_mode", "发现引擎", .text),
        .spec("monthly_spend_usd", "本月支出", .amount(currency: "USD")),
        .spec("monthly_budget_usd", "月度预算", .amount(currency: "USD")),
        .spec("eta_seconds", "预计剩余", .duration),
        .spec("expected_duration_seconds", "预计总时长", .duration),
        .spec("analysis_date", "分析日期", .dateText),
        .spec("next_scheduled_at", "下次计划", .datetimeText),
        .spec("model_requested", "请求模型", .text),
        .spec("model_used", "使用模型", .text),
        .spec("prompt_version", "提示词版本", .text),
        .spec("schema_version", "结构版本", .text),
        .spec("filter_version", "过滤版本", .text),
        .spec("failure_code", "失败代码", .text),
        .spec("failure_reason", "失败原因", .longText),
        .spec("funnel_stats", "漏斗统计", .text),
        .spec("agent_events", "代理事件", .text),
        .spec("market_context", "市场上下文", .text),
        .spec("portfolio_diagnosis", "组合诊断", .text),
        .spec("capital_flows", "资金方向", .text),
        .spec("groups", "候选分组", .text),
        .spec("raw_candidates", "原始候选", .text),
        .spec("filtered_candidates", "过滤后候选", .text),
        .spec("counts", "候选计数", .text),
        .spec("portfolio_actions", "组合动作", .text),
        .spec("limitations", "限制说明", .longText),
        .spec("raw_ticker", "原始代码", .text),
        .spec("normalized_ticker", "规范代码", .text),
        .spec("company_name", "公司名称", .text),
        .spec("exchange", "交易所", .text),
        .spec("country", "国家/地区", .text),
        .spec("raw_rank", "原始排名", .integer),
        .spec("final_rank", "最终排名", .integer),
        .spec("priority", "优先级", .text),
        .spec("symbol_match_status", "代码匹配状态", .text),
        .spec("symbol_match_reason", "代码匹配原因", .text),
        .spec("filter_status", "过滤状态", .text),
        .spec("display_status", "展示状态", .text),
        .spec("filter_reasons", "过滤原因", .longText),
        .spec("verification_status", "验证状态", .text),
        .spec("dismissed", "已忽略", .boolean(trueLabel: "已忽略", falseLabel: "正常")),
        .spec("researched", "已研究", .boolean(trueLabel: "已研究", falseLabel: "未研究")),
        .spec("discovery_reason", "发现理由", .longText),
        .spec("portfolio_fit", "组合适配", .text),
        .spec("diversification_effect", "分散化效果", .text),
        .spec("overlap_with_existing_holdings", "与现有持仓重叠", .text),
        .spec("business_quality_summary", "基本面摘要", .longText),
        .spec("investment_thesis", "投资论点", .longText),
        .spec("capital_flow_context", "资金流背景", .longText),
        .spec("valuation_context", "估值背景", .longText),
        .spec("why_now", "为何是现在", .longText),
        .spec("quality_level", "基本面档位", .text),
        .spec("valuation_level", "估值档位", .text),
        .spec("momentum_state", "动量状态", .text),
        .spec("financial_snapshot", "财务快照", .text),
        .spec("source_badges", "来源徽标", .text),
        .spec("source_count", "来源数量", .integer),
        .spec("data_discrepancies", "数据差异", .longText),
        .spec("major_risks", "主要风险", .longText),
        .spec("thesis_breakers", "论点失效条件", .longText),
        .spec("bear_case", "反方论据", .longText),
        .spec("evidence", "证据链", .text),
        .spec("research_depth", "研究深度", .text),
        .spec("reconsideration_condition", "重新考虑条件", .longText),
        .spec("input_tokens", "输入 Token", .integer),
        .spec("output_tokens", "输出 Token", .integer),
        .spec("total_tokens", "总 Token", .integer),
        .spec("finance_search_calls", "金融检索次数", .integer),
        .spec("web_search_calls", "网页检索次数", .integer),
        .spec("tool_cost_usd", "工具成本", .amount(currency: "USD")),
        .spec("model_cost_usd", "模型成本", .amount(currency: "USD")),
        .spec("total_cost_usd", "总成本", .amount(currency: "USD")),
    ])

    // MARK: Decisions / Memory

    static let decisionsFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("decision_number", "决策编号", .identifier),
        .spec("decision_type", "决策类型", .text),
        .spec("primary_symbol", "主标的", .text),
        .spec("symbols", "相关标的", .longText),
        .spec("decision_date", "决策日期", .dateText),
        .spec("time_horizon", "投资期限", .text),
        .spec("target_review_at", "计划复查", .datetimeText),
        .spec("review_due", "待复查", .boolean(trueLabel: "待复查", falseLabel: "无需复查")),
        .spec("action", "行动", .text),
        .spec("position_intent", "持仓意图", .text),
        .spec("target_weight", "目标权重", .percent(precision: 1)),
        .spec("target_quantity", "目标数量", .decimal(precision: 4)),
        .spec("target_price_min", "目标价下限", .price(precision: 2, currency: nil)),
        .spec("target_price_max", "目标价上限", .price(precision: 2, currency: nil)),
        .spec("thesis", "决策论点", .longText),
        .spec("catalysts", "催化剂", .longText),
        .spec("risks", "风险", .longText),
        .spec("invalidation_conditions", "失效条件", .longText),
        .spec("assumptions", "假设", .longText),
        .spec("open_questions", "待解问题", .longText),
        .spec("structured_conditions", "结构化条件", .text),
        .spec("memory_type", "记忆类型", .text),
        .spec("scope", "范围", .text),
        .spec("scope_key", "范围标识", .text),
        .spec("structured_value", "结构化值", .longText),
        .spec("origin", "来源", .text),
        .spec("importance", "重要性", .integer, explanation: "0–100，由服务端按使用与确认情况计算。"),
        .spec("effective_from", "生效时间", .datetimeText),
        .spec("expires_at", "过期时间", .datetimeText),
        .spec("stale_after", "过期阈值", .datetimeText),
        .spec("last_confirmed_at", "最近确认", .datetimeText),
        .spec("last_used_at", "最近使用", .datetimeText),
        .spec("supersedes_memory_id", "取代记忆", .identifier),
        .spec("supersedes_decision_id", "取代决策", .identifier),
        .spec("conflict_group", "冲突组", .identifier),
        .spec("confirmed_at", "确认时间", .datetimeText),
        .spec("archived_at", "归档时间", .datetimeText),
        .spec("resolution_type", "了结方式", .text),
        .spec("executed_trade_id", "关联交易", .identifier),
        .spec("executed_at", "执行时间", .datetimeText),
        .spec("invalidated_at", "失效时间", .datetimeText),
        .spec("closed_at", "关闭时间", .datetimeText),
        .spec("reviews", "复查记录", .text),
        .spec("live_context", "实时上下文", .text),
    ])

    // MARK: AI Chat

    static let aiChatFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("role", "角色", .text),
        .spec("conversation_id", "会话标识", .identifier),
        .spec("content", "内容", .longText),
        .spec("content_format", "内容格式", .text),
        .spec("model", "模型", .text),
        .spec("citation_count", "引用数量", .integer),
        .spec("tool_call_count", "工具调用次数", .integer),
        .spec("web_access_mode", "联网模式", .text),
        .spec("input_tokens", "输入 Token", .integer),
        .spec("output_tokens", "输出 Token", .integer),
        .spec("total_tokens", "总 Token", .integer),
        .spec("has_partial_content", "含部分内容", .boolean(trueLabel: "有部分内容", falseLabel: "完整")),
        .spec("error_message_safe", "错误信息", .longText),
        .spec("external_search_call_count", "外部检索次数", .integer),
        .spec("external_search_cost_usd", "外部检索成本", .amount(currency: "USD")),
        .spec("deep_search_run_id", "深度搜索运行", .identifier),
        .spec("generation_index", "生成序号", .integer),
        .spec("parent_message_id", "父消息", .identifier),
        .spec("reply_to_message_id", "回复消息", .identifier),
        .spec("citations", "引用", .text),
        .spec("tool_calls", "工具调用", .text),
    ])

    // MARK: Crypto

    static let cryptoFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("instrument_id", "标的标识", .identifier),
        .spec("asset_id", "资产标识", .identifier),
        .spec("display_label", "显示名称", .text),
        .spec("last_price", "最新价", .price(precision: 2, currency: nil)),
        .spec("bid_price", "买一价", .price(precision: 2, currency: nil)),
        .spec("ask_price", "卖一价", .price(precision: 2, currency: nil)),
        .spec("high_price_24h", "24 小时最高", .price(precision: 2, currency: nil)),
        .spec("low_price_24h", "24 小时最低", .price(precision: 2, currency: nil)),
        .spec("base_volume_24h", "24 小时成交量", .decimal(precision: 2)),
        .spec("quote_volume_24h", "24 小时成交额", .amount(currency: nil)),
        .spec("event_time_ms", "行情时间", .datetimeText),
        .spec("age_seconds", "数据年龄", .duration),
        .spec("closed_candle_fallback", "收盘兜底", .boolean(trueLabel: "使用收盘价", falseLabel: "实时")),
        .spec("ticker_cache", "行情缓存", .boolean(trueLabel: "缓存", falseLabel: "直连")),
        .spec("market_status", "市场状态", .text),
        .spec("next_open_at", "下次开盘", .datetimeText),
        .spec("next_close_at", "下次收盘", .datetimeText),
        .spec("time", "时间", .datetimeText),
        .spec("open_time", "开盘时间", .datetimeText),
        .spec("close_time", "收盘时间", .datetimeText),
        .spec("open", "开盘", .price(precision: 2, currency: nil)),
        .spec("high", "最高", .price(precision: 2, currency: nil)),
        .spec("low", "最低", .price(precision: 2, currency: nil)),
        .spec("close", "收盘", .price(precision: 2, currency: nil)),
        .spec("volume", "成交量", .decimal(precision: 2)),
    ])

    // MARK: Quant

    static let quantFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("strategy_key", "策略", .text),
        .spec("strategy_version", "策略版本", .text),
        .spec("instrument_ids", "标的列表", .longText),
        .spec("instrument_symbol", "标的", .text),
        .spec("parameters", "参数", .longText),
        .spec("config", "配置", .longText),
        .spec("manifest", "清单", .longText),
        .spec("manifest_hash", "清单哈希", .text),
        .spec("data_hash", "数据哈希", .text),
        .spec("feature_hash", "特征哈希", .text),
        .spec("code_hash", "代码哈希", .text),
        .spec("result_hash", "结果哈希", .text),
        .spec("seed", "随机种子", .identifier),
        .spec("metrics", "指标", .text),
        .spec("environment", "环境", .text),
        .spec("deployment_id", "部署标识", .identifier),
        .spec("deployment_status", "部署状态", .text),
        .spec("target_exposure", "目标仓位", .decimal(precision: 2), explanation: "期望仓位系数，-1 到 +1，不是订单方向。"),
        .spec("decision_time", "决策时间", .datetimeText),
        .spec("valid_from", "生效时间", .datetimeText),
        .spec("expires_at", "过期时间", .datetimeText),
        .spec("expires_in_seconds", "剩余有效", .duration),
        .spec("consumed_at", "消费时间", .datetimeText),
        .spec("consumed_reason", "消费原因", .text),
        .spec("rejected_reason", "拒绝原因", .text),
        .spec("superseded_by_id", "被取代于", .identifier),
        .spec("idempotency_key", "幂等键", .text),
        .spec("input_hash", "输入哈希", .text),
        .spec("signal_id", "信号标识", .identifier),
        .spec("date", "日期", .dateText),
        .spec("equity", "净值", .amount(currency: nil)),
        .spec("pnl", "盈亏", .amount(currency: nil)),
        .spec("entry_price", "入场价", .price(precision: 2, currency: nil)),
        .spec("exit_price", "出场价", .price(precision: 2, currency: nil)),
        .spec("definitions", "策略定义", .text),
        .spec("features", "特征", .text),
        .spec("deployments", "部署", .text),
        .spec("signals", "信号", .text),
    ])

    // MARK: PAPER

    static let paperFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("account", "账户", .text),
        .spec("account_id", "账户标识", .identifier),
        .spec("execution_mode", "执行模式", .text, explanation: "内部模拟器模式；真实交易在本客户端不可用。"),
        .spec("available_execution_modes", "可用执行模式", .longText),
        .spec("paused_at", "暂停时间", .datetimeText),
        .spec("pause_reason", "暂停原因", .text),
        .spec("initial_cash", "初始资金", .amount(currency: nil)),
        .spec("cash", "可用现金", .amount(currency: nil)),
        .spec("locked_cash", "锁定现金", .amount(currency: nil)),
        .spec("available_balance", "可用余额", .amount(currency: nil)),
        .spec("wallet_balance", "钱包余额", .amount(currency: nil)),
        .spec("equity", "权益", .amount(currency: nil)),
        .spec("nav", "净值", .amount(currency: nil), explanation: "永续保证金口径：现金 + 各持仓 (标记价 − 均价) × 数量。"),
        .spec("gross_exposure", "总敞口", .amount(currency: nil)),
        .spec("used_margin", "已用保证金", .amount(currency: nil)),
        .spec("available_margin", "可用保证金", .amount(currency: nil)),
        .spec("exposure_ratio", "敞口比例", .percent(precision: 1)),
        .spec("leverage_cap", "杠杆上限", .decimal(precision: 1)),
        .spec("costs", "成本参数", .text),
        .spec("balances", "余额明细", .text),
        .spec("positions", "持仓", .text),
        .spec("performance", "绩效", .text),
        .spec("current_run", "当前运行", .text),
        .spec("last_funding_boundary", "最近资金费边界", .datetimeText),
        .spec("last_reconciliation", "最近对账", .text),
        .spec("client_order_id", "客户端订单号", .text),
        .spec("side", "方向", .text),
        .spec("order_type", "订单类型", .text),
        .spec("market_type", "市场类型", .text),
        .spec("position_side", "持仓方向", .text),
        .spec("limit_price", "限价", .price(precision: 2, currency: nil)),
        .spec("leverage", "杠杆", .decimal(precision: 1)),
        .spec("intended_quantity", "意图数量", .decimal(precision: 6)),
        .spec("filled_quantity", "已成交数量", .decimal(precision: 6)),
        .spec("reference_price", "参考价", .price(precision: 2, currency: nil)),
        .spec("avg_fill_price", "成交均价", .price(precision: 2, currency: nil)),
        .spec("fee", "手续费", .amount(currency: nil)),
        .spec("spread_cost", "点差成本", .amount(currency: nil)),
        .spec("slippage_cost", "滑点成本", .amount(currency: nil)),
        .spec("reject_reason", "拒绝原因", .text),
        .spec("fills", "成交明细", .integer),
        .spec("liquidity", "流动性", .text),
        .spec("fill_time", "成交时间", .datetimeText),
        .spec("run_id", "运行标识", .identifier),
        .spec("job_id", "任务标识", .identifier),
        .spec("run", "运行", .text),
        .spec("runs", "运行记录", .text),
        .spec("reconciliations", "对账记录", .text),
        .spec("ledger", "账本", .text),
        .spec("repair", "修复", .text),
        .spec("status_counts", "状态计数", .text),
    ])

    // MARK: Settings

    static let settingsFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("threshold_20m", "20 分钟异动阈值", .percent(precision: 1)),
        .spec("threshold_1h", "1 小时异动阈值", .percent(precision: 1)),
        .spec("threshold_day", "日内异动阈值", .percent(precision: 1)),
        .spec("alert_cooldown_minutes", "告警冷却（分钟）", .integer),
        .spec("investigation_interval_minutes", "调查间隔（分钟）", .integer),
        .spec("investigation_duration_minutes", "调查时长（分钟）", .integer),
        .spec("price_poll_minutes", "行情轮询（分钟）", .integer),
        .spec("providers", "数据源", .text),
        .spec("redis_available", "缓存服务可用", .boolean(trueLabel: "可用", falseLabel: "不可用")),
        .spec("streaming", "流式输出", .boolean(trueLabel: "开启", falseLabel: "关闭")),
        .spec("default_model", "默认模型", .text),
        .spec("allowed_models", "可用模型", .longText),
        .spec("max_message_chars", "单条消息上限", .integer),
        .spec("conversations_enabled", "会话功能", .boolean(trueLabel: "开启", falseLabel: "关闭")),
        .spec("memory", "记忆设置", .text),
        .spec("rich_content", "富内容", .text),
        .spec("web_search", "联网检索", .text),
        .spec("last_fetch", "最近抓取", .datetimeText),
        .spec("last_success", "最近成功", .datetimeText),
        .spec("requests_today", "今日请求数", .integer),
    ])

    // MARK: Administration

    static let administrationFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("username", "用户名", .text),
        .spec("role", "角色", .text),
        .spec("quota_day", "配额日期", .dateText),
        .spec("requests_used", "已用请求", .integer),
        .spec("requests_remaining", "剩余请求", .integer),
        .spec("usable_limit", "可用上限", .integer),
        .spec("quota_timezone", "配额时区", .text),
        .spec("last_processed_ticker", "最近处理标的", .text),
        .spec("pending_profile_count", "待处理资料", .integer),
        .spec("pending_history_count", "待处理历史", .integer),
        .spec("pending_analysis_count", "待处理分析", .integer),
        .spec("failed_item_count", "失败条目", .integer),
        .spec("next_scheduled_run", "下次计划运行", .datetimeText),
        .spec("accounts", "执行账户", .text),
        .spec("agents", "执行代理", .text),
        .spec("orders", "执行订单", .text),
        .spec("events", "执行事件", .text),
    ])

    // MARK: Macro（证据区块）

    static let macroFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("provider", "数据源", .text),
        .spec("status_label_zh", "状态说明", .text),
        .spec("raw_series_count", "原始序列总数", .integer),
        .spec("available_series_count", "有数据序列", .integer),
        .spec("missing_series_keys", "缺失序列", .longText),
        .spec("latest_run_status", "最近同步状态", .text),
        .spec("errors", "错误摘要", .longText),
        .spec("state", "状态", .text),
        .spec("label_zh", "状态标签", .text),
        .spec("tone", "基调", .text),
        .spec("disclaimer", "免责说明", .longText),
        .spec("series_key", "序列标识", .text),
        .spec("display_name_zh", "指标名称", .text),
        .spec("display_name_en", "英文名称", .text),
        .spec("description_zh", "说明", .longText),
        .spec("unit", "单位", .text),
        .spec("frequency", "频率", .text),
        .spec("category", "类别", .text),
        .spec("is_derived", "派生序列", .boolean(trueLabel: "派生", falseLabel: "原始")),
        .spec("why_it_matters", "为何重要", .longText),
        .spec("rising_interpretation", "上升解读", .longText),
        .spec("falling_interpretation", "下降解读", .longText),
        .spec("bullish_scenarios", "利多情境", .longText),
        .spec("bearish_scenarios", "利空情境", .longText),
        .spec("context_notes", "口径说明", .longText),
        .spec("affected_assets", "影响资产", .longText),
        .spec("latest", "最新观察", .text),
        .spec("previous", "前一观察", .text),
        .spec("observation_date", "观察日", .dateText),
        .spec("value", "数值", .decimal(precision: 4)),
        .spec("sparkline", "走势摘要", .integer),
        .spec("current_impact", "当前影响", .text),
        .spec("trend", "趋势", .text),
        .spec("freshness", "新鲜度", .text),
        .spec("age_days", "距观察日天数", .integer),
        .spec("last_fetched_at", "最近抓取", .datetimeText),
        .spec("direction", "方向", .text),
        .spec("strength", "强度", .text),
        .spec("lookback", "回看窗口", .text),
        .spec("reason_codes", "原因代码", .longText),
        .spec("spread_10y_2y", "10Y–2Y 利差", .decimal(precision: 3)),
        .spec("spread_10y_3m", "10Y–3M 利差", .decimal(precision: 3)),
        .spec("spread_30y_5y", "30Y–5Y 利差", .decimal(precision: 3)),
        .spec("spread_10y_2y_20d", "10Y–2Y 20 日变化", .decimal(precision: 3)),
        .spec("spread_10y_2y_60d", "10Y–2Y 60 日变化", .decimal(precision: 3)),
        .spec("short_change_20d", "短端 20 日变化", .decimal(precision: 3)),
        .spec("long_change_20d", "长端 20 日变化", .decimal(precision: 3)),
        .spec("usage_date_utc", "用量日期", .dateText),
        .spec("used", "已用请求", .integer),
        .spec("successful", "成功请求", .integer),
        .spec("rate_limited", "限流请求", .integer),
        .spec("daily_limit", "每日上限", .integer),
        .spec("reserved_requests", "已预留请求", .integer),
        .spec("remaining", "剩余请求", .integer),
        .spec("automatic_remaining", "自动任务可用", .integer),
        .spec("automatic_usable_limit", "自动任务上限", .integer),
        .spec("requested_series_count", "请求序列数", .integer),
        .spec("successful_series_count", "成功序列数", .integer),
        .spec("failed_series_count", "失败序列数", .integer),
        .spec("api_requests_used", "消耗请求数", .integer),
        .spec("inserted_count", "新增数据点", .integer),
        .spec("updated_count", "更新数据点", .integer),
        .spec("unchanged_count", "未变数据点", .integer),
        .spec("mom", "环比", .text),
        .spec("yoy", "同比", .text),
        .spec("10y_2y", "10Y–2Y 序列", .integer),
        .spec("10y_3m", "10Y–3M 序列", .integer),
    ])

    // MARK: Mood（证据区块）

    static let moodFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("mood_score", "情绪评分", .decimal(precision: 1)),
        .spec("direction", "方向", .text),
        .spec("severity", "严重度", .text),
        .spec("severity_score", "严重度分值", .decimal(precision: 2)),
        .spec("persistence_sessions", "持续会话数", .integer),
        .spec("duration_sessions", "历时会话数", .integer),
        .spec("active", "活跃", .boolean(trueLabel: "活跃", falseLabel: "不活跃")),
        .spec("onset", "新触发", .boolean(trueLabel: "新触发", falseLabel: "延续")),
        .spec("resolved", "已消除", .boolean(trueLabel: "已消除", falseLabel: "仍存在")),
        .spec("first_seen", "首次出现", .dateText),
        .spec("last_seen", "最近出现", .dateText),
        .spec("evidence", "证据", .text),
        .spec("improving", "改善", .integer),
        .spec("deteriorating", "恶化", .integer),
        .spec("new_leadership", "新领涨", .integer),
        .spec("new_crowded", "新拥挤", .integer),
        .spec("strongest", "最强", .integer),
        .spec("market_mood", "市场情绪", .text),
        .spec("sector_regime", "板块状态", .text),
        .spec("ai_chain_mood", "AI 产业链情绪", .text),
        .spec("regime_changes", "状态迁移", .text),
        .spec("key_divergences", "关键背离", .text),
        .spec("crowding_signals", "拥挤信号", .text),
        .spec("sections", "分区", .text),
        .spec("scope_type", "范围类型", .text),
        .spec("scope_key", "范围", .text),
        .spec("trading_date", "交易日", .dateText),
        .spec("name_zh", "名称", .text),
        .spec("level", "层级", .text),
        .spec("candidate_state", "候选状态", .text),
        .spec("previous_state", "先前状态", .text),
        .spec("phase", "阶段", .text),
        .spec("regime", "状态体制", .text),
        .spec("agreement_score", "一致性评分", .decimal(precision: 2)),
        .spec("agreement_level", "一致性等级", .text),
        .spec("quality", "质量", .text),
        .spec("coverage", "覆盖率", .percent(precision: 0)),
        .spec("freshness_status", "新鲜度", .text),
        .spec("state_started_on", "状态起始日", .dateText),
        .spec("changed", "已变化", .boolean(trueLabel: "已变化", falseLabel: "未变化")),
        .spec("from", "从", .text),
        .spec("to", "到", .text),
        .spec("candidate", "候选", .text),
        .spec("confirmed", "已确认", .boolean(trueLabel: "已确认", falseLabel: "待确认")),
        .spec("fast_path", "快速路径", .boolean(trueLabel: "快速", falseLabel: "常规")),
        .spec("confirmation_required", "需确认", .boolean(trueLabel: "需要", falseLabel: "不需要")),
        .spec("reason_detail", "原因明细", .text),
        .spec("expected", "应有快照", .integer),
        .spec("generated", "已生成", .integer),
        .spec("missing_scopes", "缺失范围", .longText),
        .spec("insufficient_scopes", "样本不足范围", .longText),
        .spec("failed_scopes", "失败范围", .longText),
        .spec("stale_sources", "过期来源", .longText),
        .spec("duplicates", "重复项", .integer),
        .spec("calculation_version", "计算版本", .text),
        .spec("study_type", "研究类型", .text),
        .spec("state", "状态", .text),
        .spec("transition_from", "起始状态", .text),
        .spec("transition_to", "目标状态", .text),
        .spec("divergence_type", "背离类型", .text),
        .spec("bucket", "分桶", .text),
        .spec("horizon", "周期", .integer),
        .spec("sample_mode", "采样模式", .text),
        .spec("sample_count", "样本数", .integer),
        .spec("metrics", "指标", .text),
        .spec("confidence_interval", "置信区间", .text),
        .spec("median_forward_return", "中位前瞻收益", .text),
        .spec("warnings", "警告", .longText),
        .spec("event_refs", "事件引用", .text),
        .spec("mean", "均值", .decimal(precision: 4)),
        .spec("median", "中位数", .decimal(precision: 4)),
        .spec("trimmed_mean", "截尾均值", .decimal(precision: 4)),
        .spec("p25", "P25", .decimal(precision: 4)),
        .spec("p75", "P75", .decimal(precision: 4)),
        .spec("positive_rate", "上涨占比", .percent(precision: 1)),
        .spec("negative_rate", "下跌占比", .percent(precision: 1)),
        .spec("n", "样本量", .integer),
    ])

    // MARK: Industry（证据区块）

    static let industryFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("market_data", "行情数据", .text),
        .spec("total", "同步记录总数", .integer),
        .spec("freshness", "新鲜度分布", .text),
        .spec("priorities", "优先级分布", .text),
        .spec("latest_run", "最近运行", .text),
        .spec("replacement_pending", "待复核种子替换", .integer),
        .spec("failed", "失败信息", .longText),
    ])

    // MARK: Valuation / Graham

    static let valuationFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("value", "数值", .price(precision: 2, currency: nil)),
        .spec("current_price", "现价", .price(precision: 2, currency: nil)),
        .spec("margin_of_safety", "安全边际", .percent(precision: 1)),
        .spec("available", "可用", .boolean(trueLabel: "可用", falseLabel: "输入缺失")),
        .spec("graham_number", "Graham 数", .text),
        .spec("growth_formula", "增长公式", .text),
        .spec("growth_rate", "增长率 %", .decimal(precision: 2)),
        .spec("intrinsic_value", "内在价值", .price(precision: 2, currency: nil)),
        .spec("premium_or_discount", "溢价/折价", .percent(precision: 1)),
        .spec("inputs", "输入", .text),
        .spec("eps_ttm", "TTM EPS", .price(precision: 2, currency: nil)),
        .spec("book_value_per_share", "每股净资产", .price(precision: 2, currency: nil)),
        .spec("aaa_yield", "AAA 债收益率 %", .decimal(precision: 2)),
        .spec("applicability", "适用性", .text),
        .spec("overall_status", "总体状态", .text),
        .spec("financial_period", "财务期间", .text),
        .spec("data_point", "数据点", .text),
        .spec("field", "字段", .text),
        .spec("quality", "质量", .text),
        .spec("growth_rate_used", "采用增长率 %", .decimal(precision: 2)),
        .spec("growth_rate_source", "增长率来源", .text),
        .spec("growth_rate_raw", "原始增长率 %", .decimal(precision: 2)),
        .spec("growth_rate_clamped", "截断后增长率 %", .decimal(precision: 2)),
        .spec("missing_fields", "缺失输入", .longText),
    ])

    // MARK: Technical（服务端 camelCase）

    static let technicalFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("symbol", "代码", .text),
        .spec("generatedAt", "生成时间", .datetimeText),
        .spec("dataThrough", "数据截至", .dateText),
        .spec("visibleStartDate", "可见区间起", .dateText),
        .spec("visibleEndDate", "可见区间止", .dateText),
        .spec("latestClose", "最新收盘", .price(precision: 2, currency: nil)),
        .spec("weeklyTrend", "周线趋势", .text),
        .spec("nearestSupport", "最近支撑", .text),
        .spec("nearestResistance", "最近阻力", .text),
        .spec("supportZones", "支撑区", .integer),
        .spec("resistanceZones", "阻力区", .integer),
        .spec("fibonacci", "斐波那契", .text),
        .spec("trendLines", "趋势线", .integer),
        .spec("swings", "摆动点", .integer),
        .spec("indicators", "技术指标", .text),
        .spec("rsi14", "RSI(14)", .decimal(precision: 1)),
        .spec("macd", "MACD", .decimal(precision: 2)),
        .spec("macdSignal", "MACD 信号", .decimal(precision: 2)),
        .spec("macdHistogram", "MACD 柱", .decimal(precision: 2)),
        .spec("ma5", "MA5", .price(precision: 2, currency: nil)),
        .spec("ma20", "MA20", .price(precision: 2, currency: nil)),
        .spec("ma60", "MA60", .price(precision: 2, currency: nil)),
        .spec("ema20", "EMA20", .price(precision: 2, currency: nil)),
        .spec("atr14", "ATR(14)", .decimal(precision: 2)),
        .spec("weeklyMa20", "周线 MA20", .price(precision: 2, currency: nil)),
        .spec("weeklyMa50", "周线 MA50", .price(precision: 2, currency: nil)),
        .spec("bollingerLow", "布林下轨", .price(precision: 2, currency: nil)),
        .spec("bollingerHigh", "布林上轨", .price(precision: 2, currency: nil)),
        .spec("weeklyVwap", "周线 VWAP", .price(precision: 2, currency: nil)),
        .spec("confluences", "汇合点", .integer),
        .spec("omittedReasons", "省略原因", .longText),
        .spec("analysisVersion", "分析版本", .text),
    ])

    // MARK: Financials（报表科目）

    static let financialsFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("fiscal_year", "财年", .integer),
        .spec("fiscal_period", "财季", .text),
        .spec("period_end", "期末日期", .dateText),
        .spec("revenue", "营业收入", .amount(currency: nil)),
        .spec("gross_profit", "毛利润", .amount(currency: nil)),
        .spec("operating_income", "营业利润", .amount(currency: nil)),
        .spec("net_income", "净利润", .amount(currency: nil)),
        .spec("pretax_income", "税前利润", .amount(currency: nil)),
        .spec("tax_expense", "所得税费用", .amount(currency: nil)),
        .spec("eps", "每股收益", .price(precision: 2, currency: nil)),
        .spec("ebitda", "EBITDA", .amount(currency: nil)),
        .spec("cash", "现金", .amount(currency: nil)),
        .spec("inventory", "存货", .amount(currency: nil)),
        .spec("current_assets", "流动资产", .amount(currency: nil)),
        .spec("current_liabilities", "流动负债", .amount(currency: nil)),
        .spec("total_assets", "总资产", .amount(currency: nil)),
        .spec("total_liabilities", "总负债", .amount(currency: nil)),
        .spec("total_debt", "总债务", .amount(currency: nil)),
        .spec("long_term_debt", "长期债务", .amount(currency: nil)),
        .spec("shareholders_equity", "股东权益", .amount(currency: nil)),
        .spec("retained_earnings", "留存收益", .amount(currency: nil)),
        .spec("shares_issued", "发行股数", .amount(currency: nil)),
        .spec("operating_cash_flow", "经营现金流", .amount(currency: nil)),
        .spec("capital_expenditure", "资本开支", .amount(currency: nil)),
        .spec("free_cash_flow", "自由现金流", .amount(currency: nil)),
        .spec("financing_cash_flow", "融资现金流", .amount(currency: nil)),
        .spec("investing_cash_flow", "投资现金流", .amount(currency: nil)),
        .spec("depreciation", "折旧", .amount(currency: nil)),
        .spec("amortization", "摊销", .amount(currency: nil)),
    ])

    // MARK: Congress

    static let congressFields: [String: SemanticFieldSpec] = SemanticKeyDictionary.dictionary([
        .spec("buys", "近期买入", .longText),
        .spec("sells", "近期卖出", .longText),
    ])
}
