"""Provider-free deterministic quant backtesting primitives."""

from .contracts import (
    BacktestBar,
    BacktestConfig,
    BacktestInstrument,
    BacktestRunConfig,
    Bar,
    BarFeatureEvent,
    BarEvent,
    Instrument,
    InstrumentMetadata,
    InstrumentMeta,
    InstrumentSpec,
)
from .engine import (
    BacktestCancelled,
    BacktestResult,
    EquityPoint,
    LiquidationRow,
    RejectRow,
    TradeRow,
    backtest,
    run_backtest,
    run,
    simulate_backtest,
)
from .strategies import (
    DUAL_MA_STRATEGY,
    RSI_MEAN_REVERSION_STRATEGY,
    STRATEGY_REGISTRY,
    available_strategies,
    canonical_strategy_name,
    dual_ma_target,
    dual_ma_strategy,
    get_strategy,
    register_strategy,
    rsi_mean_reversion_target,
    rsi_strategy,
)

__all__ = [
    "BacktestBar",
    "BacktestCancelled",
    "BacktestConfig",
    "BacktestInstrument",
    "BacktestRunConfig",
    "BacktestResult",
    "Bar",
    "BarEvent",
    "BarFeatureEvent",
    "DUAL_MA_STRATEGY",
    "EquityPoint",
    "Instrument",
    "InstrumentMetadata",
    "InstrumentMeta",
    "InstrumentSpec",
    "LiquidationRow",
    "RejectRow",
    "RSI_MEAN_REVERSION_STRATEGY",
    "STRATEGY_REGISTRY",
    "TradeRow",
    "available_strategies",
    "canonical_strategy_name",
    "backtest",
    "dual_ma_target",
    "dual_ma_strategy",
    "get_strategy",
    "register_strategy",
    "rsi_mean_reversion_target",
    "rsi_strategy",
    "run_backtest",
    "run",
    "simulate_backtest",
]
